version: '3.8'

services: 
  postgres: 
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: passer
      POSTGRES_DB: product_management

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - '8081:8080'
  product_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: product-container
    restart: always
    ports:
      - 8085:8084
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/product_management
      SPRING_DATASOURCE_USERNAME : admin
      SPRING_DATASOURCE_PASSWORD: passer
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - postgres
      
